name: "Build image (ghcr)"

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [".github/workflows/ghcr-image.yml"]

env:
  POSTGRES_USER: "unicorn_user"
  POSTGRES_PASSWORD: "magical_password"
  POSTGRES_DB: "calendso"
  DATABASE_HOST: "database:5432"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start database
        run: docker compose up -d database

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=container:database

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/maxouf/cal.diy:latest
            ghcr.io/maxouf/cal.diy:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_WEBAPP_URL=http://localhost:3000
            NEXT_PUBLIC_API_V2_URL=http://localhost:5555/api/v2
            NEXT_PUBLIC_LICENSE_CONSENT=agree
            CALCOM_TELEMETRY_DISABLED=1
            DATABASE_URL=postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.DATABASE_HOST }}/${{ env.POSTGRES_DB }}
            DATABASE_DIRECT_URL=postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.DATABASE_HOST }}/${{ env.POSTGRES_DB }}

      - name: Cleanup
        if: always()
        run: docker compose down
